### ISSUE TITLE
[Bug] Errors when building modules to an amd style. 

### ISSUE THREAD

**Issue by BlankRain** [uber/kepler.gl#211]
**Describe the bug**
I have an old project using `requirejs` .
I want to use `kepler.gl` in my project .
when I compile the code  to amd style. I got an error.
Here is my command. I use `transform-es2015-modules-amd` to do the job.
```
$npx babel src --out-dir amd --plugins=transform-es2015-modules-amd --source-maps inline
```
**To Reproduce**
1. git clone https://github.com/uber/kepler.gl.git
2. yarn && yarn build
Now ,it all works . and has a cmd style code in dist .
3. cmd like that 
`
npx babel src --out-dir amd --plugins=transform-es2015-modules-amd --source-maps inline
`
Or
add this command to `pacakge.json` then run with `yarn amd`
`package.json`  and `scripts` blocks, add this:
`
"amd":"rm -fr amd && uber-licence && babel src --out-dir amd --plugins=transform-es2015-modules-amd --source-maps inline"
`

**Expected behavior**
A success compiled code without errors.

**Additional context**
could you show me how to use it in requirejs?

An error log in my computer.
```
yarn run v1.2.0
$ rm -fr amd && uber-licence && babel src --out-dir amd --plugins=transform-es2015-modules-amd --source-maps inline
src/actions/action-wrapper.js -> amd/actions/action-wrapper.js
src/actions/actions.js -> amd/actions/actions.js
src/actions/identity-actions.js -> amd/actions/identity-actions.js
src/actions/index.js -> amd/actions/index.js
src/actions/map-state-actions.js -> amd/actions/map-state-actions.js
src/actions/map-style-actions.js -> amd/actions/map-style-actions.js
src/actions/ui-state-actions.js -> amd/actions/ui-state-actions.js
src/actions/vis-state-actions.js -> amd/actions/vis-state-actions.js
src/components/bottom-widget.js -> amd/components/bottom-widget.js
src/components/common/checkbox.js -> amd/components/common/checkbox.js
src/components/common/color-legend.js -> amd/components/common/color-legend.js
src/components/common/dataset-label.js -> amd/components/common/dataset-label.js
src/components/common/field-selector.js -> amd/components/common/field-selector.js
src/components/common/field-token.js -> amd/components/common/field-token.js
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

warning You are using Node "9.0.0" which is not supported and may encounter bugs or unexpected behavior. Yarn supports the following semver range: "^4.8.0 || ^5.7.0 || ^6.2.2 || ^8.0.0"
TypeError: src/components/common/file-uploader/file-upload.js: Property consequent of ConditionalExpression expected node to beof a type ["Expression"] but instead got null
    at Object.validate (/home/brain/codespace/github/kepler.gl/node_modules/babel-types/lib/definitions/index.js:109:13)
    at Object.validate (/home/brain/codespace/github/kepler.gl/node_modules/babel-types/lib/index.js:505:9)
    at NodePath._replaceWith (/home/brain/codespace/github/kepler.gl/node_modules/babel-traverse/lib/path/replacement.js:176:7)
    at NodePath._remove (/home/brain/codespace/github/kepler.gl/node_modules/babel-traverse/lib/path/removal.js:58:10)
    at NodePath.remove (/home/brain/codespace/github/kepler.gl/node_modules/babel-traverse/lib/path/removal.js:30:8)
    at PluginPass.CallExpression (/home/brain/codespace/github/kepler.gl/node_modules/babel-plugin-transform-es2015-modules-amd/lib/index.js:61:12)
    at NodePath._call (/home/brain/codespace/github/kepler.gl/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/home/brain/codespace/github/kepler.gl/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/home/brain/codespace/github/kepler.gl/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/home/brain/codespace/github/kepler.gl/node_modules/babel-traverse/lib/context.js:150:16)
error Command failed with exit code 1.


```

**Comment by BlankRain** [comment]
https://github.com/babel/babel/issues/8567#issuecomment-416579546

**Comment by BlankRain** [comment]
replys from https://github.com/babel/babel/issues/8567#issuecomment-416579546
```
I have tested your repository with Babel 7 and it builds fine when using @babel/plugin-transform-modules-amd. Unfortunately you can't update yet because one of your dependencies (babel-tape-runner) uses babel-register@6. If I manually patch that module (node_modules/babel-tape-runner/bin/babel-tape-runner, every seems to work.I suggest opening a PR to that repository and then updating yours
--
```

**Comment by BlankRain** [comment]
@heshan0131  Could you update  babel6 to babel7 ? so we can close this issue.
 nicolo-ribaudo shows the details of `packages.json` and `.bablerc` in http://github.com/babel/babel/issues/8567#issuecomment-416872061
