### ISSUE TITLE
Example application build failure, Cannot find module 'babel-plugin-inline-json-import'

### ISSUE THREAD

**Issue by techieBrandon** [uber/kepler.gl#359]
I'm unable to build the example application(s) from the example directory, recieving the following response: Cannot find module 'babel-plugin-inline-json-import'

Naturally, I assume someone missed a install for the module and go attempt to fix myself. However, that then leads me down a bit of a rabbit hole. Feels like something simple is missing but I'm not certain what it is.

Side note: I've been through all the vis.academy tutorials/examples without any build issues.

macOS 10.14.2

```
users-mbp:SkunkWorks secret.user$ git clone https://github.com/uber/kepler.gl.git
Cloning into 'kepler.gl'...
remote: Enumerating objects: 143, done.
remote: Counting objects: 100% (143/143), done.
remote: Compressing objects: 100% (113/113), done.
remote: Total 7422 (delta 49), reused 86 (delta 29), pack-reused 7279
Receiving objects: 100% (7422/7422), 16.50 MiB | 864.00 KiB/s, done.
Resolving deltas: 100% (5154/5154), done.
users-mbp:SkunkWorks secret.user$ cd kepler.gl/
users-mbp:kepler.gl secret.user$ cd examples/demo-app/
users-mbp:demo-app secret.user$ yarn --ignore-engines && yarn start
yarn install v1.13.0
warning package.json: No license field
info No lockfile found.
warning No license field
[1/4] 🔍  Resolving packages...
warning kepler.gl > react-file-drop@0.1.9: Please update to 0.2.2+ for support of the latest react, improved browser support, and typescript definitions
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > react-palm@1.3.1" has incorrect peer dependency "react@^16.4.1".
warning " > react-palm@1.3.1" has unmet peer dependency "react-test-renderer@^16.4.1".
warning " > react-redux@4.4.9" has unmet peer dependency "redux@^2.0.0 || ^3.0.0".
warning "kepler.gl > react-palm > react-dom@16.8.1" has incorrect peer dependency "react@^16.0.0".
warning "kepler.gl > react-markdown > html-to-react@1.3.4" has incorrect peer dependency "react@^16.0".
warning "kepler.gl > react-palm > react-reconciler@0.12.0" has incorrect peer dependency "react@^16.0.0".
warning "kepler.gl > react-palm > react-test-renderer@16.8.1" has incorrect peer dependency "react@^16.0.0".
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
✨  Done in 40.24s.
yarn run v1.13.0
warning package.json: No license field
$ webpack-dev-server --progress --hot --open
 10% building 1/1 modules 0 activeℹ ｢wds｣: Project is running at http://localhost:8080/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: 404s will fallback to /index.html
 10% building 3/3 modules 0 activeℹ ｢wdm｣: wait until bundle finished: /     
✖ ｢wdm｣: Hash: 973d8066e7ea8f001b65                                            
Version: webpack 4.29.3
Time: 4222ms
Built at: 02/14/2019 12:18:14 PM
 2 assets
Entrypoint app = bundle.js bundle.js.map
 [0] (webpack)/hot/log.js 1.11 KiB {0} [built]
 [3] (webpack)/hot/emitter.js 75 bytes {0} [built]
 [4] multi (webpack)-dev-server/client?http://localhost:8080 (webpack)/hot/dev-server.js ./src/main.js 52 bytes {0} [built]
 [5] (webpack)-dev-server/client?http://localhost:8080 7.78 KiB {0} [built]
 [6] ./node_modules/url/url.js 22.8 KiB {0} [built]
 [7] ./node_modules/node-libs-browser/node_modules/punycode/punycode.js 14.3 KiB {0} [built]
 [9] ./node_modules/url/util.js 314 bytes {0} [built]
[13] ./node_modules/strip-ansi/index.js 161 bytes {0} [built]
[15] ./node_modules/loglevel/lib/loglevel.js 7.68 KiB {0} [built]
[16] (webpack)-dev-server/client/socket.js 1.05 KiB {0} [built]
[18] (webpack)-dev-server/client/overlay.js 3.58 KiB {0} [built]
[23] (webpack)/hot sync nonrecursive ^\.\/log$ 170 bytes {0} [built]
[25] (webpack)/hot/dev-server.js 1.61 KiB {0} [built]
[26] (webpack)/hot/log-apply-result.js 1.27 KiB {0} [built]
[27] ./src/main.js 2.8 KiB {0} [built] [failed] [1 error]
    + 13 hidden modules

WARNING in configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/concepts/mode/

ERROR in ./src/main.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find module 'babel-plugin-inline-json-import' from '/Users/secret.user/Development/SkunkWorks/kepler.gl/examples/demo-app'

users-mbp:demo-app secret.user$ nvm ls
        v11.6.0
->      v11.9.0
         system
default -> 11.9.0 (-> v11.9.0)
node -> stable (-> v11.9.0) (default)
stable -> 11.9 (-> v11.9.0) (default)
iojs -> N/A (default)
unstable -> N/A (default)
lts/* -> lts/dubnium (-> N/A)
lts/argon -> v4.9.1 (-> N/A)
lts/boron -> v6.16.0 (-> N/A)
lts/carbon -> v8.15.0 (-> N/A)
lts/dubnium -> v10.15.1 (-> N/A)
users-mbp:demo-app secret.user$ npm --version
6.5.0
users-mbp:demo-app secret.user$ yarn --version
1.13.0


users-mbp:demo-app secret.user$ npm install babel-plugin-inline-json-import --save
npm WARN deprecated react-file-drop@0.1.9: Please update to 0.2.2+ for support of the latest react, improved browser support, and typescript definitions
npm WARN rm not removing /Users/secret.user/Development/ViaviSolutions/SkunkWorks/kepler.gl/examples/demo-app/node_modules/.bin/json5 as it wasn't installed by /Users/secret.user/Development/ViaviSolutions/SkunkWorks/kepler.gl/examples/demo-app/node_modules/json5

> fsevents@1.2.7 install /Users/secret.user/Development/ViaviSolutions/SkunkWorks/kepler.gl/examples/demo-app/node_modules/fsevents
> node install

node-pre-gyp WARN Using needle for node-pre-gyp https download 
[fsevents] Success: "/Users/secret.user/Development/ViaviSolutions/SkunkWorks/kepler.gl/examples/demo-app/node_modules/fsevents/lib/binding/Release/node-v67-darwin-x64/fse.node" is installed via remote
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN react-tooltip@3.3.0 requires a peer of react-dom@^0.14.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-palm@1.3.1 requires a peer of react@^16.4.1 but none is installed. You must install peer dependencies yourself.
npm WARN react-dom@16.8.1 requires a peer of react@^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN html-to-react@1.3.4 requires a peer of react@^16.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-test-renderer@16.8.1 requires a peer of react@^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-reconciler@0.12.0 requires a peer of react@^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN demo-app No repository field.
npm WARN demo-app No license field.

+ babel-plugin-inline-json-import@0.3.1
added 70 packages from 33 contributors, removed 79 packages, updated 974 packages and audited 12967 packages in 109.171s
found 1 moderate severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
users-mbp:demo-app secret.user$ yarn --ignore-engines && yarn start
yarn install v1.13.0
warning package.json: No license field
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
warning No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > react-palm@1.3.1" has incorrect peer dependency "react@^16.4.1".
warning " > react-palm@1.3.1" has unmet peer dependency "react-test-renderer@^16.4.1".
warning " > react-redux@4.4.9" has unmet peer dependency "redux@^2.0.0 || ^3.0.0".
warning "kepler.gl > react-markdown > html-to-react@1.3.4" has incorrect peer dependency "react@^16.0".
warning "kepler.gl > react-palm > react-dom@16.8.1" has incorrect peer dependency "react@^16.0.0".
warning "kepler.gl > react-palm > react-reconciler@0.12.0" has incorrect peer dependency "react@^16.0.0".
warning "kepler.gl > react-palm > react-test-renderer@16.8.1" has incorrect peer dependency "react@^16.0.0".
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
✨  Done in 5.94s.
yarn run v1.13.0
warning package.json: No license field
$ webpack-dev-server --progress --hot --open
 10% building 1/1 modules 0 activeℹ ｢wds｣: Project is running at http://localhost:8080/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: 404s will fallback to /index.html
 10% building 3/3 modules 0 activeℹ ｢wdm｣: wait until bundle finished: /     
✖ ｢wdm｣: Hash: a328491f60d84c3a193f                                            
Version: webpack 4.29.3
Time: 4629ms
Built at: 02/14/2019 12:37:31 PM
 2 assets
Entrypoint app = bundle.js bundle.js.map
 [0] (webpack)/hot/log.js 1.11 KiB {0} [built]
 [3] (webpack)/hot/emitter.js 75 bytes {0} [built]
 [4] multi (webpack)-dev-server/client?http://localhost:8080 (webpack)/hot/dev-server.js ./src/main.js 52 bytes {0} [built]
 [5] (webpack)-dev-server/client?http://localhost:8080 7.78 KiB {0} [built]
 [6] ./node_modules/url/url.js 22.8 KiB {0} [built]
 [7] ./node_modules/node-libs-browser/node_modules/punycode/punycode.js 14.3 KiB {0} [built]
 [9] ./node_modules/url/util.js 314 bytes {0} [built]
[13] ./node_modules/strip-ansi/index.js 161 bytes {0} [built]
[15] ./node_modules/loglevel/lib/loglevel.js 7.68 KiB {0} [built]
[16] (webpack)-dev-server/client/socket.js 1.05 KiB {0} [built]
[18] (webpack)-dev-server/client/overlay.js 3.58 KiB {0} [built]
[23] (webpack)/hot sync nonrecursive ^\.\/log$ 170 bytes {0} [built]
[25] (webpack)/hot/dev-server.js 1.61 KiB {0} [built]
[26] (webpack)/hot/log-apply-result.js 1.27 KiB {0} [built]
[27] ./src/main.js 2.38 KiB {0} [built] [failed] [1 error]
    + 13 hidden modules

WARNING in configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/concepts/mode/

ERROR in ./src/main.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find module '/Users/secret.user/Development/ViaviSolutions/SkunkWorks/kepler.gl/examples/demo-app/src/@babel/runtime/helpers/interopRequireDefault'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:609:15)
    at Function.Module._load (internal/modules/cjs/loader.js:535:25)
    at Module.require (internal/modules/cjs/loader.js:663:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at requireFresh (/Users/secret.user/Development/ViaviSolutions/SkunkWorks/kepler.gl/examples/demo-app/node_modules/babel-plugin-inline-json-import/build/index.js:115:10)
    at requireModule (/Users/secret.user/Development/ViaviSolutions/SkunkWorks/kepler.gl/examples/demo-app/node_modules/babel-plugin-inline-json-import/build/index.js:109:10)
    at /Users/secret.user/Development/ViaviSolutions/SkunkWorks/kepler.gl/examples/demo-app/node_modules/babel-plugin-inline-json-import/build/index.js:53:26
    at Array.map (<anonymous>)
    at PluginPass.exit (/Users/secret.user/Development/ViaviSolutions/SkunkWorks/kepler.gl/examples/demo-app/node_modules/babel-plugin-inline-json-import/build/index.js:46:50)
    at newFn (/Users/secret.user/Development/ViaviSolutions/SkunkWorks/kepler.gl/examples/demo-app/node_modules/@babel/traverse/lib/visitors.js:193:21)
    at NodePath._call (/Users/secret.user/Development/ViaviSolutions/SkunkWorks/kepler.gl/examples/demo-app/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/Users/secret.user/Development/ViaviSolutions/SkunkWorks/kepler.gl/examples/demo-app/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/Users/secret.user/Development/ViaviSolutions/SkunkWorks/kepler.gl/examples/demo-app/node_modules/@babel/traverse/lib/path/context.js:97:8)
    at TraversalContext.visitQueue (/Users/secret.user/Development/ViaviSolutions/SkunkWorks/kepler.gl/examples/demo-app/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitSingle (/Users/secret.user/Development/ViaviSolutions/SkunkWorks/kepler.gl/examples/demo-app/node_modules/@babel/traverse/lib/context.js:90:19)
    at TraversalContext.visit (/Users/secret.user/Development/ViaviSolutions/SkunkWorks/kepler.gl/examples/demo-app/node_modules/@babel/traverse/lib/context.js:146:19)
 @ multi (webpack)-dev-server/client?http://localhost:8080 (webpack)/hot/dev-server.js ./src/main.js app[2]
ℹ ｢wdm｣: Failed to compile.




```

**Comment by techieBrandon** [comment]
Modifying examples/demo-app/.babelrc to remove the plugin "inline-json-import" and then removing the json-loader rule from examples/demo-app/webpack.config.js seems to have resolved the issue for me.

I notice a few sample datasets imported at the top of app.js but not certain what other json there would be the inline during the bable transpile. I don't see any hanging issues right now.

**Comment by macrigiuseppe** [comment]
Found issue and fixed: https://github.com/uber/kepler.gl/pull/362

**Comment by macrigiuseppe** [comment]
@techieBrandon can you let us know if the problem still persists?
We have merged the fix for this
